#!/usr/bin/env zsh

echo "[INFO] - Install Brew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

(echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/thughes/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

echo "[INFO] - Install Brew Tooling"
visit_brewery

.macos 
.dock
