#!/usr/bin/env zsh

INSTALL_DIR="$(dirname ${0:A})"


if ! command -v brew &> /dev/null; then
    echo "[Error] Must Install Brew." >&2
    exit 1
fi
echo "[INFO] - Root Install Dir [$INSTALL_DIR]"

echo "[INFO] - Install Brew Tooling"
visit_brewery "$INSTALL_DIR"

echo "[INFO] - Config Mac Settings"
.macos 

echo "[INFO] - Config Dock" 
.dock

echo "[INFO] - Install and Configure Oh My Zsh"
# ZSH should be installed, but we'll re-install it just in case. 
brew install zsh 
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

cp "$INSTALL_DIR/resources/mackie.zsh-theme" ~/.oh-my-zsh/themes/
open "$INSTALL_DIR/resources/dotfile.itermcolors"

# Set ZSH RC
rm ~/.zshrc
ln -s "$INSTALL_DIR/.zshrc" ~/.zshrc

# Make Bin Files Executable 
chmod -R +x "$INSTALL_DIR/bin"
